#!/bin/sh

#	 _
#	| |__  ___ _ ____      ___ __ ___  _ __ ___
#	| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#	| |_) \__ \ |_) \ V  V /| | | | | | | | (__
#	|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#	          |_|

#Killall Programs
killall -9 polybar sxhkd dunst nitrogen udiskie picom #nm-applet blueman-applet pasystray

#Polybar
exec $HOME/.config/bspwm/scripts/launchBar.sh &

#Start Hotkey Deamon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

#Compositor
picom --config $HOME/.config/bspwm/picom.conf --experimental-backends &

#Set Wallpaper
exec $HOME/.config/bspwm/scripts/background.sh &
#nitrogen --restore

#Fix Cursor
xsetroot -cursor_name left_ptr &

#Notification
dunst -config $HOME/.config/bspwm/dunstrc &

#Automounting
udiskie &

#For Hiding Cursor while typing
xbanish &

# For System Tray
# nm-applet &
# blueman-applet &
# pasystray &

# Settings
bspc monitor -d I II III IV V VI VII 
bspc config border_width		2
bspc config normal_border_color		"#d3869b"
bspc config focused_border_color 	"#7daea3"
bspc config single_monocle		false
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer 	true

###---Desktop Settings----###
bspc config top_padding 		36
bspc config bottom_padding 		2
bspc config left_padding 		10
bspc config right_padding 		10
bspc config window_gap 			8

# Rules
# bspc rule -a Brave-browser desktop='^2'
bspc rule -a Spotify desktop='^5'
bspc rule -a Gimp state=floating 
bspc rule -a photoshop state=floating
bspc rule -a Zathura state=tiled
