#!/bin/sh

#	 _____  _| |__ | | ____| |_ __ ___
#	/ __\ \/ / '_ \| |/ / _` | '__/ __|
#	\__ \>  <| | | |   < (_| | | | (__
#	|___/_/\_\_| |_|_|\_\__,_|_|  \___|


# quit/restart bspwm
super + shift + {q,r}
	bspc {quit,wm -r}

# close and kill
super + shift + c
	bspc node -c

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#Setting Wallpaper
Insert
	$HOME/.config/bspwm/scripts/background.sh

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

#Toogle Floating 
super + shift + f
	bspc node focused.tiled -t floating || bspc node focused.floating -t tiled

#Toogle Fullscreen 
super + f
	bspc node focused.tiled -t fullscreen || bspc node focused.fullscreen -t tiled

#Toogle Gaps
super + shift + equal
	$HOME/.config/bspwm/scripts/gaps.sh

super + shift + p
	$HOME/.config/bspwm/scripts/$TERMINAL.sh
	
# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# preselect the direction
super + alt + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + Escape
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel || bspc node -p cancel

###  Resize and Move ###
#
# expand a window by moving one of its side outward
super + ctrl + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
ctrl + alt + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

###  Mouse Resize and Move  ###
super + {z,x}
    bspc config pointer_action1 {move,resize_corner}

# Brighness control
XF86MonBrightnessUp
	xbacklight -inc 10		

XF86MonBrightnessDown
	xbacklight -dec 10		

#Audio Control
XF86AudioRaiseVolume
	pamixer --allow-boost -i 10

XF86AudioLowerVolume
	pamixer -d 10

XF86AudioMute
	pamixer -t 

#Screenshot
Print
	flameshot screen -p /home/sdk/Pictures/Screenshot

super + Print
	flameshot gui

#Applications
super + w
	$BROWSER

super + n
  $TERMINAL -e nvim

super + m
	$TERMINAL -e ncmpcpp

super + o
  $TERMINAL -e ranger

#Run Launchers
super + space
	rofi -show drun -theme gruvbox-dark-hard.rasi -icon-theme "Tela-circle" -show-icons
	
super + shift + Return
	dmenu_run -p "Run  :"
	
# terminal emulator
super + Return
	$TERMINAL
 
# ScratchPads with tdrop
super + p
	tdrop -ma -w 70% -h 65% -y 17% -x 15% -n 1 $TERMINAL -e htop

super + r
	tdrop -ma -w 70% -h 65% -y 17% -x 15% -n 2 $TERMINAL -e lfub

super + c
	tdrop -ma -w 70% -h 65% -y 17% -x 15% -n 3 $TERMINAL -e tty-clock -c -s -t -B -C 7

super + y
	tdrop -ma -w 70% -h 65% -y 17% -x 15% -n 2 $TERMINAL
